### PR TITLE
Mastery Exercise submission

### PR DESCRIPTION
**Pull request by vaughnwalters**

### CODE REVIEW

**Comment by vaughnwalters** [comment]
@morecallan

**Comment by vaughnwalters** [comment]
@morecallan MVP

**Comment by morecallan** [comment]
@vaughnwalters This is looking stellar. 

👍 for use of es6, for solid commit history, for clear comments and clear variable names
👍 👍 for reaching MVP with some impressive code. 

Definitely showing a strong grasp of Milestone 1 concepts. 

Before you merge:
-Run an npm install of "event-stream" with a `--save` on it. (That way it gets added to your package.json and whenever anyone pulls down your project and runs  `npm install`, it will automatically download that package. 
-Maybe change the variable name on the limit-10 transformer in your main file so it is clear what is happening inside the pipeline.

Overall, great work. Let me know if you have any questions!

**Comment by vaughnwalters** [comment]
@morecallan i did have a question about naming that transform stream , so i'm glad you said something.  is the "_transform" always convention, or should that be changed as well?  so like `limit-ten._transform` or `limit-ten._limit-ten`?

**Comment by morecallan** [comment]
@vaughnwalters 

The _transform naming convention cannot be altered because that's the pre-packaged method that all Transform streams need to use to pass the stream through them. 

> All Transform stream implementations must provide a _transform() method to accept input and produce output. 

So it would be `limit-ten._transform`. `my_awesome_transform_stream._transform = () =>` `monkeybutt._transform` etc.

**Comment by vaughnwalters** [comment]
@morecallan okay rad, thanks

**Comment by morecallan** [comment]
👍 merge away!

**Pull request merged**
